version: '3'

# Usage start sudo ./firsteponly.sh

services:
  ftpd_server:
    image: stilliard/pure-ftpd:hardened-latest
    container_name: pure-ftpd
    ports:
      - "${FTP_PORT}:21"
      - "30000-30009:30000-30009"
    expose:
      - "30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "./data:/home"
      - "./userpasswd:/etc/pure-ftpd/passwd"
      - "./logs:/var/log"
# comment if no  ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
      - "./ssl:/etc/ssl/private"
    environment:
      PUBLICHOST: "localhost"
      FTP_PASSIVE_PORTS: "30000:30009"
      FTP_USER_NAME: ${FTP_USER}
      FTP_USER_PASS: ${FTP_USER_PASSWORD}
      FTP_USER_HOME: ${FTP_USER_HOME}
      TLS_CN: localhost
      TLS_ORG: ${TLS_ORGANISATION}
      TLS_C: ${TLS_COUNTRY}
      TLS_USE_DSAPRAM: "true"
# comment if no ssl/tls:
      ADDED_FLAGS: "-d -d --tls=2"
    
    restart: unless-stopped
